### ISSUE TITLE
5.19 fails to compile on alpha

### ISSUE THREAD

**Issue by matoro** [strace/strace#220]
Hi, 5.18 builds but 5.19 fails to compile on alpha, kernel+headers 5.19.

```
alpha-unknown-linux-gnu-gcc -DHAVE_CONFIG_H   -I./linux/alpha -I./linux/alpha -I./linux/generic -I./linux/generic -I. -I. -I../bundled/linux/arch/alpha/include/uapi -I../bundled/linux/include/uapi -DIN_STRACE=1      -I./bundled/linux/arch/alpha/include/uapi -I./bundled/linux/include/uapi -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wformat-security -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wtrampolines -Wundef -Wwrite-strings  -mieee -O2 -pipe -mcpu=ev4 -c -o libstrace_a-printsiginfo.o `test -f 'printsiginfo.c' || echo './'`printsiginfo.c
In file included from printsiginfo.c:16:
printsiginfo.c: In function ‘print_si_info’:
printsiginfo.c:191:50: error: ‘siginfo_t’ has no member named ‘si_trapno’; did you mean ‘si_errno’?
  191 |                         PRINT_FIELD_XVAL_D(*sip, si_trapno, alpha_trap_codes,
      |                                                  ^~~~~~~~~
defs.h:1854:17: note: in definition of macro ‘sign_extend_unsigned_to_ll’
 1854 |         (sizeof(v) == sizeof(char) ? (long long) (char) (v) : \
      |                 ^
```

(lots of repeats in the same file, just including the meaningful error here)

Presumably caused by https://github.com/strace/strace/commit/9fd4989f7d14f4213627d521626fbecdd52838eb?

Maybe this kernel change is related?  https://lore.kernel.org/lkml/87h7gvxx7l.fsf_-_@disp2133/

**Comment by cyborgyn** [comment]
This is also the issue with 5.10 kernel+headers.

**Comment by ldv-alt** [comment]
Looks like [an old glibc bug](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=4c0a1e6392fc9f667dba272dc13d94dc5c54813e).

Likely the following sysdeps/unix/sysv/linux/alpha/bits/siginfo-arch.h would fix it:
```
/* Architecture-specific adjustments to siginfo_t.  Alpha version.  */
#ifndef _BITS_SIGINFO_ARCH_H
#define _BITS_SIGINFO_ARCH_H 1

#define __SI_SIGFAULT_ADDL \
  int _si_trapno;

#define si_trapno	_sifields._sigfault._si_trapno

#endif
```

**Comment by ldv-alt** [comment]
OK, it's a glibc bug, but thanks to https://github.com/torvalds/linux/commit/add0b32ef914 glibc is out of sync with the kernel both on alpha and sparc, so a different glibc fix is needed.

**Comment by ldv-alt** [comment]
Filed [a bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=30173) to glibc bugzilla, applying a workaround.
