### ISSUE TITLE
Bundled headers update did not add time_types.h

### ISSUE THREAD

**Issue by 3x380V** [strace/strace#405]
Linux fixed  timespec64 definition in _90079798f1d7 ("delayacct: fix uapi timespec64 definition")_ and since then `linux/taskstats.h` needs `linux/time_types.h`. This change was brought into strace with 33b9507, which didn't add `linux/time_types.h` so the build fails with:
```
In file included from ../bundled/linux/include/uapi/linux/cgroupstats.h:20,
                 from netlink_nlctrl.c:11:
../bundled/linux/include/uapi/linux/taskstats.h:21:10: fatal error: linux/time_types.h: No such file or directory
   21 | #include <linux/time_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

Sorry for not providing PR right away; `linux/time_types.h` needs `__kernel_old_time_t`:
```
In file included from ../bundled/linux/include/uapi/linux/taskstats.h:21,
                 from ../bundled/linux/include/uapi/linux/cgroupstats.h:20,
                 from netlink_nlctrl.c:11:
../bundled/linux/include/uapi/linux/time_types.h:32:9: error: unknown type name '__kernel_old_time_t'; did you mean '__kernel_old_gid_t'?
   32 |         __kernel_old_time_t     tv_sec;         /* seconds */
      |         ^~~~~~~~~~~~~~~~~~~
      |         __kernel_old_gid_t
```
That's in `asm/posix_types.h` included through `linux/types.h`, but despite later is in tree for a long time, the former is not, thus I wonder how is `--enable-bundled` supposed to work.

**Comment by ldv-alt** [comment]
The regression (unconditional use of linux/time_types.h) was introduced by commit 33b950714a966bde816a1f1e75c127c3d3ae53cd.

**Comment by 3x380V** [comment]
That seems to be what the second sentence of the issue claims. So again, how is `--enable-bundled` supposed to work? Should be bundled headers self contained? If so, see https://github.com/strace/strace/compare/master...3x380V:strace:fix-bundled
and if that's way to go I'll add proper commit message, sign-off, etc... or adjust the fix according to suggestions.

**Comment by 3x380V** [comment]
@ldv-alt, the alternative would be updating to UAPI headers v7.1-rcX while adding missing files... (and delayed update of linux/io_uring.h)
