### ISSUE TITLE
Fails to compile on parisc with linux-headers >= 6.15

### ISSUE THREAD

**Issue by matoro** [strace/strace#371]
Since https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=fd87b7783802b45cdd261b273e6b2b792823064d , strace fails to compile on parisc (hppa):
```
hppa2.0-unknown-linux-gnu-gcc -DHAVE_CONFIG_H   -I./linux/hppa -I./linux/hppa -I./linux/generic -I./linux/generic -I. -I. -isystem ../bundled/linux/arch/parisc/include/uapi -isystem ../bundled/linux/include/uapi -DIN_STRACE=1      -isystem ./bundled/linux/arch/parisc/include/uapi -isystem ./bundled/linux/include/uapi -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wformat-security -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wtrampolines -Wundef -Wwrite-strings  -O2 -pipe -march=2.0 -c -o libstrace_a-msghdr.o `test -f 'msghdr.c' || echo './'`msghdr.c
In file included from static_assert.h:11,
                 from macros.h:16,
                 from list.h:90,
                 from defs.h:40,
                 from msghdr.c:13:
xlat/scmvals.h:102:1: error: static assertion failed: "SCM_DEVMEM_LINEAR != 0x4e"
  102 | static_assert((SCM_DEVMEM_LINEAR) == (0x4e), "SCM_DEVMEM_LINEAR != 0x4e");
      | ^~~~~~~~~~~~~
xlat/scmvals.h:109:1: error: static assertion failed: "SCM_DEVMEM_DMABUF != 0x4f"
  109 | static_assert((SCM_DEVMEM_DMABUF) == (0x4f), "SCM_DEVMEM_DMABUF != 0x4f");
      | ^~~~~~~~~~~~~
make[3]: *** [Makefile:6455: libstrace_a-msghdr.o] Error 1
```
Downstream report:  https://bugs.gentoo.org/965573

**Comment by matoro** [comment]
I tried applying this patch on top of 6.18, but I still get the same error.  Is something else needed?  I can provide access to a dev box if it would help.

**Comment by ldv-alt** [comment]
> I tried applying this patch on top of 6.18, but I still get the same error. Is something else needed? I can provide access to a dev box if it would help.

Yes, this would be helpful.

**Comment by matoro** [comment]
> > I tried applying this patch on top of 6.18, but I still get the same error. Is something else needed? I can provide access to a dev box if it would help.
> 
> Yes, this would be helpful.

Sure thing!  I've provisioned you an account [on my sandbox here](https://static.matoro.tk/isa-sandbox-faq.html) with your pubkeys.  You can log in as `g-ldv`.  Let me know if that's helpful.

**Comment by ldv-alt** [comment]
> Sure thing! I've provisioned you an account [on my sandbox here](https://static.matoro.tk/isa-sandbox-faq.html) with your pubkeys. You can log in as `g-ldv`. Let me know if that's helpful.

Hmm, I've tried various keys but failed to log in. What are the keys you've been using?

**Comment by matoro** [comment]
> > Sure thing! I've provisioned you an account [on my sandbox here](https://static.matoro.tk/isa-sandbox-faq.html) with your pubkeys. You can log in as `g-ldv`. Let me know if that's helpful.
> 
> Hmm, I've tried various keys but failed to log in. What are the keys you've been using?

Oops, accidentally had a typo in the username.  Try now

**Comment by ldv-alt** [comment]
I've successfully built commit 4e0e92d11b2c7044a9b4d1abece8ed65b11f1a51, so the original build issue is indeed fixed, but quite a few tests don't pass on that box because the filesystem being used doesn't match expectations.

**Comment by matoro** [comment]
Sorry about that, I just raised the issue in IRC and the reason was pointed out to me, I tested it by applying the patch on top of a release tarball, which already had pregenerated xlat headers, so it had no effect.  It works when regenerating them, my apologies and thank you for the great work!  Please feel free to use any of the available machines in the future if you want to test platform-specific stuff.
